### ISSUE TITLE
NPE when dying to an impact with a bouncy block

### ISSUE THREAD

**Issue by Cervator** [Terasology/FunnyBlocks#6]
Noted while testing #5 - other than the stacktrace I didn't actually notice any ill effects. Without the log visible you might not notice at all. Probably a quick null hardening would fix it.

Protip: Jumping as you're hitting a bouncy block can make you go REALLY high! :D

```
1:16:40.418 [main] ERROR o.t.e.event.internal.EventSystemImpl - Failed to invoke event
java.lang.NullPointerException: null
	at org.terasology.funnyblocks.system.BouncySystem.onCharacterMovement(BouncySystem.java:46)
	at org.terasology.funnyblocks.system.BouncySystemMethodAccess.invoke(Unknown Source)
	at org.terasology.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:506)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:269)
	at org.terasology.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:260)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:145)
	at org.terasology.logic.players.LocalPlayerSystem.processInput(LocalPlayerSystem.java:173)
	at org.terasology.logic.players.LocalPlayerSystem.update(LocalPlayerSystem.java:144)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:160)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:413)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:368)
	at org.terasology.engine.Terasology.main(Terasology.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by Setako** [comment]
I think it could fix the NPE bug:
https://github.com/Terasology/FunnyBlocks/pull/5/commits/1e557f374d9eeebdd8b45b84cbede18ef07fa92d
But I haven't got this error yet, would you like to test more one time for my new commit please?

**Comment by Cervator** [comment]
Yep that fixed it! Thanks :-)
